info:
  namespace: sunnova
items:
  celestial_fist:
    display_name: "Sunnova"
    permission: sunnova
    resource:
      material: DIAMOND_SWORD
      model_id: 8201
      generate: false
      model_path: sunnova_model/celestial_fist
  sun_god:
    display_name: "Sun God Nika"
    permission: sun_god
    resource:
      material: COAL 
      generate: false
      model_path: sunnova_model/sun_god